### ISSUE TITLE
Not work well on windows 10.

### ISSUE THREAD

**Issue by Weissle** [vincarlet/vf3-parallel#4]
I used visual studio to debug vf3p ( MSVC V142 ;  Windows 10 SDK 10.0.18362.0 ) and encountered an error because of invalid comparator ( Maybe because STL not allow  A < B if   B < A ).

This error exist in ARGraph.hpp,line 649,  if(!e_attributemap.count(edge_attr)){...
 ( commit 5fa8a02 ; commit on Mar 18,2020 ) I think it exists in previous commit too.

And it work well on WSL Ubuntu 18.04LTS. 
Could you solve it ?

**Comment by vincarlet** [comment]
Thanks, try with the new version published on the new repo: https://github.com/MiviaLab/vf3lib
